### ISSUE TITLE
Unable to download weight

### ISSUE THREAD

**Issue by life97** [chengchunhsu/EveryPixelMatters#14]
I cannot download the weight. Could you please provide the weight? Thank you!

![Uploading 权重无法下载.png…]()

**Comment by chengchunhsu** [comment]
Hi, I just re-uploaded all files [here](https://drive.google.com/drive/folders/17Clx1QpI5VpowaxKV_SXWsd8A8WwP9ys).

**Comment by life97** [comment]
> Hi, I just re-uploaded all files [here](https://drive.google.com/drive/folders/17Clx1QpI5VpowaxKV_SXWsd8A8WwP9ys).

Thank you!
