### ISSUE TITLE
google drive link doesn't work

### ISSUE THREAD

**Issue by nimaone** [chengchunhsu/EveryPixelMatters#17]
i want to download model and dataset but google drive's link doesn't exist. can someone help me to download the converted annotation of [Sim10k (VOC format)](https://drive.google.com/file/d/1WoEPsG-u1aaGv-RiRy1b-ixtPYhsteVw/view?usp=sharing) and [Cityscapes (COCO format)](https://drive.google.com/file/d/1LRNXW2Wee8tjuxc5gjVsFQv49vA_SBtk/view?usp=sharing).

**Comment by BinhuiXie** [comment]
+1

**Comment by chengchunhsu** [comment]
Hi, I just re-uploaded all files [here](https://drive.google.com/drive/folders/17Clx1QpI5VpowaxKV_SXWsd8A8WwP9ys).

**Comment by bimsarapathiraja** [comment]
This doesn't work either
