### ISSUE TITLE
Does your code write detections on images? Or read the detection from pth files and plot them?

### ISSUE THREAD

**Issue by mamunir** [chengchunhsu/EveryPixelMatters#2]

**Comment by chengchunhsu** [comment]
Hi @mamunir,

During the evaluation stage, our code will evaluate the result in mAP and save it as a JSON file (COCO format).
After that, you can plot the result or do anything else via the COCO API with the saved file.

Let me know if you have any further questions!

Cheng-Chun

**Comment by mamunir** [comment]
@chengchunhsu , sorry for coming on this thread late. I was primarily trying to run this code on original and custom datasets. After the success to that, I pursue this post.
Couple of questions are that bbox.json you saved as detection file is after NMS or before? Secondly, can you point out which file helps me in drawing dets using COCO API?
